export const SONDAGE_DETAILS_REQUEST = ' SONDAGE_DETAILS_REQUEST';
export const SONDAGE_DETAILS_SUCCESS = 'SONDAGE_DETAILS_SUCCESS';
export const SONDAGE_DETAILS_FAIL = 'SONDAGE_DETAILS_FAIL';
export const SONDAGE_TOKEN = 'SONDAGE_TOKEN';