export const SONDAGE_DETAILS_REQUEST = ' SONDAGE_DETAILS_REQUEST';
export const SONDAGE_DETAILS_SUCCESS = 'SONDAGE_DETAILS_SUCCESS';
export const SONDAGE_DETAILS_FAIL = 'SONDAGE_DETAILS_FAIL';
export const SONDAGE_TOKEN = 'SONDAGE_TOKEN';

export const GET_SONDAGES_REQUEST = 'GET_SONDAGES_REQUEST';
export const GET_SONDAGES_SUCCESS = 'GET_SONDAGES_SUCCESS';
export const GET_SONDAGES_FAIL = 'GET_SONDAGES_FAIL';